config/routes.rb
AgoraSample::Application.routes.draw do
  resources :accounts

  root :to => "accounts#index"
end

app/models/account.rb
class Account < ActiveRecord::Base
	validates :first_name, :presence => true, :format => /\A[a-z ]+\z/i
	validates :last_name, :presence => true, :format => /\A[a-z '-]+\z/i
	validates :address1, :presence => true, :format => /\A[a-z0-9 \.]+\z/i
	validates :city, :presence => true, :format => /\A[a-z \.]+\z/i
	validates :state, :presence => true
	validates :zip, :presence => true, :format => /\A(\d{5}|\d{9})\z/
	validates :phone, :length => {:minimum => 10}, :numericality => true, :allow_blank => true
	validates :email, :presence => true, :format => /\A[a-z\d._%+-]+@(?:[a-z\d-]+\.)+[a-z]{2,4}\z/i
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def index
		if params[:search]
			@accounts = Account.order(:last_name).where("last_name = ? OR first_name = ?", 
																																			params[:search], params[:search])
		else
			@accounts = Account.order(:last_name)
		end
	end

	def new
		@account = Account.new
	end

	def create
		@account = Account.new(params[:account])

		respond_to do |format|
			if @account.save
				Resque.enqueue(VerifyAccount, @account.id)
				format.html { redirect_to accounts_path, :notice => "Account was successfully created." }
				format.xml  { render :xml => @account, :status => :created, :location => @account }
				format.json { render :json => @account, :status => :created, :location => @account }
			else
				format.html { render 'new' }
				format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
				format.json { render :json => @account.errors, :status => :unprocessable_entity }
			end
		end
	end

	def edit
		@account = Account.find(params[:id])
	end

	def update
		@account = Account.find(params[:id])

		if @account.update_attributes(params[:account])
			redirect_to accounts_path, :notice => "Account was successfully updated."
		else
			render 'edit'
		end
	end

	def destroy
		@account = Account.find(params[:id])
		@account.destroy
		redirect_to accounts_path, :notice => "Account successfully deleted."
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/accounts_helper.rb
module AccountsHelper
	def states_collection
		[
			["Alabama", "AL"],
			["Alaska", "AK"],
			["Arizona", "AZ"],
			["Arkansas", "AR"],
			["California", "CA"],
			["Colorado", "CO"],
			["Connecticut", "CT"],
			["Delaware", "DE"],
			["District of Columbia", "DC"],
			["Florida", "FL"],
			["Georgia", "GA"],
			["Hawaii", "HI"],
			["Idaho", "ID"],
			["Illinois", "IL"],
			["Indiana", "IN"],
			["Iowa", "IA"],
			["Kansas", "KS"],
			["Kentucky", "KY"],
			["Louisiana", "LA"],
			["Maine", "ME"],
			["Maryland", "MD"],
			["Massachusetts", "MA"],
			["Michigan", "MI"],
			["Minnesota", "MN"],
			["Mississippi", "MS"],
			["Missouri", "MO"],
			["Montana", "MT"],
			["Nebraska", "NE"],
			["Nevada", "NV"],
			["New Hampshire", "NH"],
			["New Jersey", "NJ"],
			["New Mexico", "NM"],
			["New York", "NY"],
			["North Carolina", "NC"],
			["North Dakota", "ND"],
			["Ohio", "OH"],
			["Oklahoma", "OK"],
			["Oregon", "OR"],
			["Pennsylvania", "PA"],
			["Rhode Island", "RI"],
			["South Carolina", "SC"],
			["South Dakota", "SD"],
			["Tennessee", "TN"],
			["Texas", "TX"],
			["Utah", "UT"],
			["Vermont", "VT"],
			["Virginia", "VA"],
			["Washington", "WA"],
			["West Virginia", "WV"],
			["Wisconsin", "WI"],
			["Wyoming", "WY"]
		]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/accounts/_form.html.erb
<%= form_for @account do |f| %>
	<%= f.error_messages %>

	<div class="field">
		<%= f.label :first_name %>*<br />
		<%= f.text_field :first_name %>
	</div>
	<div class="field">
		<%= f.label :last_name %>*<br />
		<%= f.text_field :last_name %>
	</div>
	<div class="field">
		<%= f.label :address1 %>*<br />
		<%= f.text_field :address1 %>
	</div>
	<div class="field">
		<%= f.label :address2 %><br />
		<%= f.text_field :address2 %>
	</div>
	<div class="field">
		<%= f.label :city %>*<br />
		<%= f.text_field :city %>
	</div>
	<div class="field">
		<%= f.label :state %>*<br />
		<%= f.select :state, states_collection, :prompt => "Select State" %>
	</div>
	<div class="field">
		<%= f.label :zip %>*<br />
		<%= f.text_field :zip, :size => 9, :maxlength => 9 %>
	</div>
	<div class="field">
		<%= f.label :phone %><br />
		<%= f.text_field :phone, :size => 10, :maxlength => 10 %>
	</div>
	<div class="field">
		<%= f.label :email %>*<br />
		<%= f.text_field :email %>
	</div>
	<div class="submit">
		<%= f.submit %>
	</div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Edit Account</h1>

<%= render "form" %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<%= form_tag accounts_path, :method => :get do %>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "Search" %>
<% end %>

<br />

<table>
	<tr>
		<th>Last</th>
		<th>First</th>
		<th>Email</th>
		<th>Verified</th>
		<th></th>
		<th></th>
	</tr>

<% @accounts.each do |account| %>
	<tr>
		<td><%= account.last_name %></td>
		<td><%= account.first_name %></td>
		<td><%= account.email %></td>
		<td><%= account.verified ? "Yes" : "No" %></td>
		<td><%= link_to "Edit", edit_account_path(account) %></td>
		<td><%= link_to "Delete", account, :confirm => "Are you sure?", :method => :delete %></td>
	</tr>
<% end %>
</table>

<br />

<%= link_to "New Account", new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>